apiVersion: apps/v1
kind: Deployment
metadata:
  name: project_nature
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project_nature
  template:
    metadata:
      labels:
        app: project_nature
    spec:
      containers:
      - name: project_nature
        image: project_nature:v1
        resources:
          limits:
            memory: "512Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: project_nature
spec:
  selector:
    app: project_nature
  ports:
  - port: 1234
    targetPort: 8080

