apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: project_nature
spec:
  name: project_nature
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: project_nature
          image: project_nature:v1
          resources:
            limits:
              memory: "512Mi"
              cpu: "200m"
          ports:
          - containerPort: 8080
            name: http
    graph:
      children: []
      endpoint:
        type: REST
      name: project_nature
      type: MODEL
    name: project_nature
    replicas: 1